JANGLE_VERSION = '0.1.0'

require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require 'rake/gempackagetask'

task :default => [:test]

Rake::TestTask.new('test') do |t|
  t.libs << 'lib'
  t.pattern = 'test/tc_*.rb'
  t.verbose = true
  t.ruby_opts = ['-r marc', '-r test/unit']
end

spec = Gem::Specification.new do |s|
  s.name = 'jangle'
  s.version = JANGLE_VERSION
  s.author = 'Ross Singer'
  s.email = 'rossfsinger@gmail.com'
  s.homepage = 'http://jangle.org/'
  s.platform = Gem::Platform::RUBY
  s.summary = 'A ruby library for creating Jangle interfaces'
  s.files = Dir.glob("{lib}/**/*") + ["Rakefile", "README", "Changes",
    "LICENSE"]
  s.has_rdoc = true
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end

Rake::RDocTask.new('doc') do |rd|
  rd.rdoc_files.include("lib/**/*.rb")
  rd.main = 'jangle'
  rd.rdoc_dir = 'doc'
end
